services:
  app:
    build: .
    restart: always
    volumes:
      - ./.env:/app/.env:ro
    networks:
      internal:
      default:

networks:
  default:
    driver: bridge
  internal:
    internal: true
